name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  checks:

    runs-on: ubuntu-24.04

    steps:

    - uses: actions/checkout@v4

    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

    - name: Install dependencies symfony
      run: composer install --working-dir=src/gql
    
    - name: Install dependencies php-cs-fixer
      run: composer install --working-dir=src/gql/tools/php-cs-fixer

    - name: Run php-cs-fixer
      working-directory: src/gql/
      run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix

    - name: Run phpunit
      working-directory: src/gql/
      run: php bin/phpunit

